#!/usr/bin/env zsh

code --install-extension abusaidm.html-snippets
code --install-extension alexcvzz.vscode-sqlite
code --install-extension almenon.arepl
code --install-extension atlassian.atlascode
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension davidbabel.vscode-simpler-icons
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EFanZh.graphviz-preview
code --install-extension emilast.LogFileHighlighter
code --install-extension ericadamski.carbon-now-sh
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension figstack.vsc
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.copilot
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.debug-visualizer
code --install-extension HookyQR.minify
code --install-extension James-Yu.latex-workshop
code --install-extension joaompinto.vscode-graphviz
code --install-extension keewek.compare-helper
code --install-extension KevinRose.vsc-python-indent
code --install-extension lei.theme-chromodynamics
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension magicstack.MagicPython
code --install-extension mechatroner.rainbow-csv
code --install-extension moshfeu.compare-folders
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.test-adapter-converter
code --install-extension msrvida.vscode-sanddance
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-sqlite
code --install-extension njpwerner.autodocstring
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rogalmic.bash-debug
code --install-extension rogalmic.zsh-debug
code --install-extension shardulm94.trailing-spaces
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sidthesloth.html5-boilerplate
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension trond-snekvik.simple-rst
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-nested-tags.vscode-nested-tags
code --install-extension wix.vscode-import-cost
code --install-extension wwm.better-align
code --install-extension yzhang.markdown-all-in-one
code --install-extension aaron-bond.better-comments
